#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edil.com.br" # the base hostname & protocol for your site, e.g. http://example.com


remote_theme: yous/whiteglass

