#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edil.com.br" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
highlighter: rouge

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-target-blank

paginate: 12
paginate_path: "/blog/page/:num"


# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slugified_categories/:slug
  projects:
    output: true
    permalink: /project/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"


# Tags
tag_page_dir:         blog/tag
tag_page_layout:      tag_page
tag_permalink_style:  /blog/:title

sass:
  sass_dir: _sass
  style: compressed
