#-------------------------------
# Site Settings

title: Edil Medeiros
logo: # You can add own logo. For example '/images/logo.png'.
description: 

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About Me'
      url: '/about/'
    - title: 'Publications'
      submenu:
      - url: '/academic-publications'
        title: 'Academic'
      - url: '/other-publications'
        title: 'Non Academic'
    - title: Blog
      url: /blog/

# Call to action button
cta__button__text: Get in touch

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Edil Medeiros
  title: Hello! I’m Edil Medeiros
  bio: I'm an Associate Professor at the <a href="http://www.ene.unb.br/" rel="noopener noreferrer" target="_blank">Electrical Engineering Department</a> at the <a href="https://unb.br/" rel="noopener noreferrer" target="_blank">University of Brasília</a>, in the political capital of Brazil.<br><br>I lecture on several courses ranging from analog to digital electronics, embedded systems, and functional programming. You can find most of them on my <a href="http://youtube.com/profedil" rel="noopener noreferrer" target="_blank">Youtube channel</a> (the videos are in Brazilian Portuguese, though).<br><br>My research interests focus on digital signal processing techniques (in particular, point clouds geometry compression) and model-based engineering design flows.<br><br>On the social side, I was the founder of the Classical Liberal Intitute of the Center-West and of the <a href="https://iflbrasil.com.br/unidades-ifl/ifl-brasilia/" rel="noopener noreferrer" target="_blank">Leadership Development Institute of Brasília</a>.
  image: '/images/avatar_edil.jpg'
  avatar: '/images/avatar_edil.jpg'
  button__text: See my works


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Works</span> # Add a 'text-span' class to highlight text.
  projects__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section

# testimonial__title: My Happy <span class="text-span">Clients</span> # Add a 'text-span' class to highlight text.

# testimonial-items:
#   - name: "Zaire Baptista"
#     image: "/images/client-1.jpg"
#     designation : "Traveler"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

#   - name: "Ann Philips"
#     image: "/images/client-2.jpg"
#     designation : "Designer"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

#   - name: "Roger Bergson"
#     image: "/images/client-3.jpg"
#     designation : "CEO, Founder"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

#   - name: "Julie Arnold"
#     image: "/images/client-4.jpg"
#     designation : "Full stack developer"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">Posts</span> # Add a 'text-span' class to highlight text.
  blog__description: 


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: jose.edil+site@gmail.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
# mailchimp__settings:
#   mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
#   mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/edil_medeiros"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/edil.medeiros"}
- {icon: "ion-logo-youtube", link: "https://youtube.com/@edilmedeiros"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/edilmedeiros/"}
- {icon: "ion-logo-github", link: "https://github.com/edilmedeiros"}
